### ISSUE TITLE
[BUG] super confusing

### ISSUE THREAD

**Issue by ardissaps** [lukebemish/cobbled_paths#2]
why not add path automatically with just builting shovel, tried every way on description page does not work on single path, not even path on creative tab to build to.

**Comment by lukebemish** [comment]
1) Craft a sett (try using a stonecutter)
2) Use it on a path

**Comment by ardissaps** [comment]
> 1. Craft a sett (try using a stonecutter)
> 2. Use it on a path

ok, some suggestion use shovel right click related block could be more convenient (with spesific tier are abble if too OP), like wood shovel only can do dirt path, cobbled path need stone shovel or above but simply right click like vanilla and blockus path block. In addition creative inventory block without tool. No hurry I love your other ones mods! Have a nice day!

**Comment by lukebemish** [comment]
Using a shovel to right click a block makes a vanilla path.
