### ISSUE TITLE
[Port] No 1.19.2 version available

### ISSUE THREAD

**Issue by Sshmoob** [lukebemish/cobbled_paths#5]
You have a version for 1.19.3, but not 1.19.2, which most mods are still stuck on. Could you port the mod to this version? Thanks in advance.

**Comment by lukebemish** [comment]
I will not be porting the mod to 1.19.2 myself. I develop exclusively for the latest version, with the exception of fixing major bugs or security flaws. If you would like to use the mod for 1.19.2 - I am certainly not against releasing a 1.19.2 version, but will not be porting it myself.
